// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace VaccineChecker.Models
{
    [Table("student")]
    public partial class student
    {
        [Key]
        public int NationalID { get; set; }
        [StringLength(150)]
        public string name { get; set; }
        [StringLength(200)]
        public string email { get; set; }
        [StringLength(40)]
        public string faculty { get; set; }
        public bool? vaccined { get; set; }
        public byte[] certificateImage { get; set; }
        public byte[] personalImage { get; set; }
    }
}