// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace VaccineChecker.Models
{
    public partial class user
    {
        [Key]
        [StringLength(50)]
        public string username { get; set; }
        [StringLength(50,MinimumLength =8)]
        public string password { get; set; }
        public bool? isadmin { get; set; }
    }
}